import React from "react";
import {Jumbotron as Jumbo, Container}

const Jumbotron = () => (
    <Jumbo fluid className="jumbo">
    <div className="overlay"></div>
    <Container>
    <h1> ROEMA </h1>
    <P>LOREM DIASHDJSA HKJDHJKSHAKDJHKSAJHDJKASHJKDHSAUKDHKSAJHDJKHSKJHDKJSHDSAEHWjdbgshgdjs
    LOREM DIASHDJSA HKJDHJKSHAKDJHKSAJHDJKASHJKDHSAUKDHKSAJHDJKHSKJHDKJSHDSAEHWjdbgshgdjs
    LOREM DIASHDJSA HKJDHJKSHAKDJHKSAJHDJKASHJKDHSAUKDHKSAJHDJKHSKJHDKJSHDSAEHWjdbgshgdjs
    LOREM DIASHDJSA HKJDHJKSHAKDJHKSAJHDJKASHJKDHSAUKDHKSAJHDJKHSKJHDKJSHDSAEHWjdbgshgdjs</P>
    LOREM DIASHDJSA HKJDHJKSHAKDJHKSAJHDJKASHJKDHSAUKDHKSAJHDJKHSKJHDKJSHDSAEHWjdbgshgdjs
    
    </Container>
    </Jumbo>
)